version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: vuong
      MONGO_INITDB_ROOT_PASSWORD: 02011996
    volumes:
      - /home/vuong/mongodata:/data/db