version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 11038:27017
    restart: always
    volumes:
      - /home/vuong/Desktop/Data/mongodb:/data/db

